language: julia
os:
  - linux
  - osx
julia:
  - release
  - nightly
matrix:
  allow_failures:
  - julia: nightly
notifications:
  email: false
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'Pkg.clone(pwd()); Pkg.build("Crispulator"); Pkg.test("Crispulator", coverage=true)';
after_success:
  - julia -e 'cd(Pkg.dir("Crispulator")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
  - julia -e 'Pkg.add("Documenter")'
  - julia -e 'cd(Pkg.dir("Crispulator")); include(joinpath("docs", "make.jl"))'
